import {
  clampExpiry, PLAYBACK_SECONDS, StorageError, UPLOAD_SECONDS,
  type CompletedPart, type MediaStorageProvider, type MultipartUpload,
  type ObjectMetadata, type SignedUrlOptions, type UploadOptions,
} from "./provider.js";
import { encodeKey, presign, signRequest, type SigningCredentials } from "./sigv4.js";

/**
 * CLOUDFLARE R2, OVER THE S3 API, WITH BARE FETCH.
 *
 * R2 speaks S3 well enough that this class is really "an S3-compatible
 * provider that defaults to R2's conventions". The three differences that
 * matter, and each one has bitten somebody:
 *
 *  1. **Region is `auto`** and is still signed. Sending a real region works;
 *     sending none does not.
 *  2. **No `x-amz-checksum-*` by default.** AWS's own SDK began sending CRC32
 *     checksums on every request, which R2 rejects. Not using the SDK means
 *     not having that argument.
 *  3. **Path-style addressing.** `https://<account>.r2.cloudflarestorage.com/<bucket>/<key>`,
 *     not `<bucket>.<host>`. Virtual-host style also works on R2, but path
 *     style is what the endpoint Cloudflare gives you in the dashboard is,
 *     and mixing the two is how a signature ends up covering a different host
 *     from the one the request reaches.
 *
 * ## Errors
 *
 * S3 answers with an XML document and an HTTP status. The status alone is not
 * enough — a 403 is a wrong key, an expired signature, a clock skew and a
 * missing permission, and telling them apart is most of the work of getting
 * a bucket configured for the first time. So `fail()` carries the store's own
 * `<Code>` and `<Message>` through, exactly as `packages/ai`'s `transcribe()`
 * carries the provider's words: the store has already diagnosed the problem
 * better than we could.
 *
 * ## Why the XML is parsed with regular expressions
 *
 * Because it is not general XML. Five documents are read here, all of them
 * machine-generated by S3, all of them flat, and all of them wanted for one
 * or two scalar fields. A parser dependency to read `<UploadId>` would be the
 * largest thing in this package.
 */

export interface R2Config {
  /** `https://<accountid>.r2.cloudflarestorage.com` */
  endpoint: string;
  bucket: string;
  accessKeyId: string;
  secretAccessKey: string;
  /** R2: "auto". A real S3: the bucket's region. */
  region?: string;
  /** For tests and self-hosted S3 (MinIO): use `<endpoint>/<bucket>/<key>`. */
  forcePathStyle?: boolean;
  fetchImpl?: typeof fetch;
  now?: () => Date;
}

const tag = (xml: string, name: string): string | null => {
  const m = new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`).exec(xml);
  return m ? decodeXml(m[1]!) : null;
};

const blocks = (xml: string, name: string): string[] => {
  const out: string[] = [];
  const re = new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`, "g");
  for (let m = re.exec(xml); m; m = re.exec(xml)) out.push(m[1]!);
  return out;
};

const decodeXml = (s: string): string =>
  s.replace(/&lt;/g, "<").replace(/&gt;/g, ">").replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'").replace(/&amp;/g, "&");

const encodeXml = (s: string): string =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&#39;");

/** ETags come back quoted, and a quoted etag will not match an unquoted one. */
const unquote = (v: string | null): string | null => (v ? v.replace(/^"|"$/g, "") : null);

export class R2StorageProvider implements MediaStorageProvider {
  readonly name = "cloudflare-r2";
  private readonly creds: SigningCredentials;
  private readonly endpoint: string;
  private readonly bucket: string;
  private readonly pathStyle: boolean;
  private readonly doFetch: typeof fetch;
  private readonly now: () => Date;

  constructor(cfg: R2Config) {
    if (!cfg.endpoint) throw new StorageError("R2 endpoint is not configured.", 500);
    if (!cfg.bucket) throw new StorageError("R2 bucket is not configured.", 500);
    if (!cfg.accessKeyId || !cfg.secretAccessKey) {
      throw new StorageError("R2 credentials are not configured.", 500);
    }
    this.endpoint = cfg.endpoint.replace(/\/+$/, "");
    this.bucket = cfg.bucket;
    this.pathStyle = cfg.forcePathStyle ?? true;
    this.doFetch = cfg.fetchImpl ?? fetch;
    this.now = cfg.now ?? (() => new Date());
    this.creds = {
      accessKeyId: cfg.accessKeyId,
      secretAccessKey: cfg.secretAccessKey,
      region: cfg.region || "auto",
      service: "s3",
    };
  }

  private url(key: string, query?: Record<string, string>): string {
    const base = this.pathStyle
      ? `${this.endpoint}/${encodeURIComponent(this.bucket)}/${encodeKey(key)}`
      : `${this.endpoint.replace("://", `://${this.bucket}.`)}/${encodeKey(key)}`;
    if (!query || !Object.keys(query).length) return base;
    const qs = new URLSearchParams(query).toString();
    return `${base}?${qs}`;
  }

  private async send(args: {
    method: string; key: string; query?: Record<string, string>;
    headers?: Record<string, string>; body?: Uint8Array;
  }): Promise<Response> {
    const signed = signRequest({
      creds: this.creds,
      method: args.method,
      url: this.url(args.key, args.query),
      headers: args.headers,
      body: args.body,
      now: this.now(),
    });
    try {
      return await this.doFetch(signed.url, {
        method: args.method,
        headers: signed.headers,
        body: args.body ? (args.body as unknown as BodyInit) : undefined,
        cache: "no-store",
      });
    } catch (e) {
      throw new StorageError(
        `Could not reach object storage: ${(e as Error)?.message ?? "network error"}`, 503, e,
      );
    }
  }

  /** Turn the store's XML complaint into a sentence with its own words in it. */
  private async fail(res: Response, what: string): Promise<never> {
    const body = await res.text().catch(() => "");
    const code = tag(body, "Code");
    const message = tag(body, "Message");
    const detail = [code, message].filter(Boolean).join(": ") || res.statusText;
    const status = res.status === 404 ? 404 : res.status === 403 ? 502 : res.status;
    throw new StorageError(`${what} failed (${res.status}) — ${detail.slice(0, 300)}`, status);
  }

  private metaFromHeaders(key: string, res: Response, fallbackSize = 0): ObjectMetadata {
    const len = Number(res.headers.get("content-length"));
    const modified = res.headers.get("last-modified");
    return {
      key,
      size: Number.isFinite(len) && len >= 0 ? len : fallbackSize,
      contentType: res.headers.get("content-type"),
      etag: unquote(res.headers.get("etag")),
      lastModified: modified ? new Date(modified) : null,
    };
  }

  async upload(key: string, body: Uint8Array, opts: UploadOptions = {}): Promise<ObjectMetadata> {
    const headers: Record<string, string> = {
      "content-type": opts.contentType || "application/octet-stream",
      "content-length": String(body.byteLength),
    };
    // The store enforces it, not us: two racing writers cannot both win.
    if (opts.ifAbsent) headers["if-none-match"] = "*";
    for (const [k, v] of Object.entries(opts.metadata ?? {})) {
      headers[`x-amz-meta-${k.toLowerCase()}`] = v;
    }
    const res = await this.send({ method: "PUT", key, headers, body });
    if (res.status === 412) throw new StorageError("An object already exists at that key.", 409);
    if (!res.ok) await this.fail(res, "Upload");
    return {
      key, size: body.byteLength,
      contentType: headers["content-type"]!,
      etag: unquote(res.headers.get("etag")),
      lastModified: this.now(),
    };
  }

  async createSignedUploadUrl(key: string, opts: SignedUrlOptions = {}): Promise<string> {
    /*
     * No `content-type` in the signed headers, deliberately. A browser sets
     * its own on a PUT — `MediaRecorder` blobs carry `video/webm;codecs=vp9,opus`
     * with spacing the browser chooses — and any mismatch with what we signed
     * is a SignatureDoesNotMatch that reads like a credentials problem. The
     * real content type is recorded in our own row, which is the copy anything
     * downstream reads.
     */
    return presign({
      creds: this.creds,
      method: "PUT",
      url: this.url(key),
      expiresIn: clampExpiry(opts.expiresIn, UPLOAD_SECONDS),
      now: this.now(),
    });
  }

  async createMultipartUpload(key: string, opts: UploadOptions = {}): Promise<MultipartUpload> {
    const headers: Record<string, string> = {
      "content-type": opts.contentType || "application/octet-stream",
    };
    for (const [k, v] of Object.entries(opts.metadata ?? {})) {
      headers[`x-amz-meta-${k.toLowerCase()}`] = v;
    }
    const res = await this.send({ method: "POST", key, query: { uploads: "" }, headers });
    if (!res.ok) await this.fail(res, "Starting a multipart upload");
    const uploadId = tag(await res.text(), "UploadId");
    if (!uploadId) throw new StorageError("The store did not return an upload id.", 502);
    return { key, uploadId };
  }

  async signUploadPart(
    key: string, uploadId: string, partNumber: number, opts: SignedUrlOptions = {},
  ): Promise<string> {
    if (!Number.isInteger(partNumber) || partNumber < 1 || partNumber > 10_000) {
      throw new StorageError(`Part number ${partNumber} is out of range.`, 400);
    }
    return presign({
      creds: this.creds,
      method: "PUT",
      url: this.url(key),
      expiresIn: clampExpiry(opts.expiresIn, UPLOAD_SECONDS),
      query: { partNumber: String(partNumber), uploadId },
      now: this.now(),
    });
  }

  async completeMultipartUpload(
    key: string, uploadId: string, parts: CompletedPart[],
  ): Promise<ObjectMetadata> {
    if (!parts.length) throw new StorageError("A multipart upload needs at least one part.", 400);
    const ordered = [...parts].sort((a, b) => a.partNumber - b.partNumber);
    const body = new TextEncoder().encode(
      `<CompleteMultipartUpload>${ordered
        .map((p) => `<Part><PartNumber>${p.partNumber}</PartNumber><ETag>${encodeXml(`"${p.etag.replace(/^"|"$/g, "")}"`)}</ETag></Part>`)
        .join("")}</CompleteMultipartUpload>`,
    );
    const res = await this.send({
      method: "POST", key, query: { uploadId },
      headers: { "content-type": "application/xml", "content-length": String(body.byteLength) },
      body,
    });
    if (!res.ok) await this.fail(res, "Completing the upload");
    /*
     * S3 can answer 200 and STILL have failed — the body is streamed so the
     * connection can be held open, and an error arrives as an <Error> element
     * inside a 200. Anyone who trusts the status here eventually ships a
     * "successful" upload that produced no object.
     */
    const text = await res.text();
    if (/<Error>/.test(text)) {
      const detail = [tag(text, "Code"), tag(text, "Message")].filter(Boolean).join(": ");
      throw new StorageError(`Completing the upload failed — ${detail || "unknown error"}`, 502);
    }
    const meta = await this.getMetadata(key);
    if (!meta) throw new StorageError("The assembled object is not in the store.", 502);
    return meta;
  }

  async abortMultipartUpload(key: string, uploadId: string): Promise<void> {
    const res = await this.send({ method: "DELETE", key, query: { uploadId } });
    // 404 means it is already gone, which is the state we wanted.
    if (!res.ok && res.status !== 404) await this.fail(res, "Abandoning the upload");
  }

  async listUploadedParts(key: string, uploadId: string): Promise<CompletedPart[]> {
    const out: CompletedPart[] = [];
    let marker: string | null = null;
    for (let page = 0; page < 100; page++) {
      const query: Record<string, string> = { uploadId, "max-parts": "1000" };
      if (marker) query["part-number-marker"] = marker;
      const res: Response = await this.send({ method: "GET", key, query });
      if (res.status === 404) return out;           // nothing started, or already gone
      if (!res.ok) await this.fail(res, "Listing the uploaded parts");
      const text = await res.text();
      for (const part of blocks(text, "Part")) {
        const n = Number(tag(part, "PartNumber"));
        const etag = unquote(tag(part, "ETag"));
        if (Number.isInteger(n) && etag) out.push({ partNumber: n, etag });
      }
      if (tag(text, "IsTruncated") !== "true") break;
      marker = tag(text, "NextPartNumberMarker");
      if (!marker) break;
    }
    return out.sort((a, b) => a.partNumber - b.partNumber);
  }

  async createSignedDownloadUrl(key: string, opts: SignedUrlOptions = {}): Promise<string> {
    const query: Record<string, string> = {};
    if (opts.downloadAs) {
      query["response-content-disposition"] =
        `attachment; filename="${opts.downloadAs.replace(/["\\]/g, "_")}"`;
    }
    if (opts.contentType) query["response-content-type"] = opts.contentType;
    return presign({
      creds: this.creds,
      method: "GET",
      url: this.url(key),
      expiresIn: clampExpiry(opts.expiresIn, PLAYBACK_SECONDS),
      query,
      now: this.now(),
    });
  }

  async getMetadata(key: string): Promise<ObjectMetadata | null> {
    const res = await this.send({ method: "HEAD", key });
    if (res.status === 404) return null;
    if (!res.ok) await this.fail(res, "Reading the object");
    return this.metaFromHeaders(key, res);
  }

  async read(key: string): Promise<Uint8Array> {
    const res = await this.send({ method: "GET", key });
    if (res.status === 404) throw new StorageError("That object is not in the store.", 404);
    if (!res.ok) await this.fail(res, "Downloading the object");
    return new Uint8Array(await res.arrayBuffer());
  }

  async copy(fromKey: string, toKey: string, opts: { contentType?: string } = {}): Promise<ObjectMetadata> {
    /*
     * CopyObject: a PUT on the destination naming the source in
     * `x-amz-copy-source` as `/<bucket>/<key>`. The bytes move inside the
     * store; the response is a small XML document, not the object.
     */
    const headers: Record<string, string> = {
      "x-amz-copy-source": `/${encodeURIComponent(this.bucket)}/${encodeKey(fromKey)}`,
      "x-amz-metadata-directive": opts.contentType ? "REPLACE" : "COPY",
    };
    if (opts.contentType) headers["content-type"] = opts.contentType;
    const res = await this.send({ method: "PUT", key: toKey, headers });
    if (res.status === 404) throw new StorageError("That object is not in the store.", 404);
    if (!res.ok) await this.fail(res, "Copying the object");
    const meta = await this.getMetadata(toKey);
    if (!meta) throw new StorageError("The copy did not appear in the store.", 502);
    return meta;
  }

  async delete(keys: string[]): Promise<void> {
    const list = keys.filter(Boolean);
    if (!list.length) return;
    /*
     * DeleteObjects takes 1000 at a time and answers 200 with per-key
     * outcomes; a key that was not there counts as deleted, which is the
     * idempotence the retention sweep relies on.
     */
    for (let i = 0; i < list.length; i += 1000) {
      const batch = list.slice(i, i + 1000);
      const body = new TextEncoder().encode(
        `<Delete><Quiet>true</Quiet>${batch
          .map((k) => `<Object><Key>${encodeXml(k)}</Key></Object>`)
          .join("")}</Delete>`,
      );
      const { createHash } = await import("node:crypto");
      const res = await this.send({
        method: "POST", key: "", query: { delete: "" },
        headers: {
          "content-type": "application/xml",
          "content-length": String(body.byteLength),
          // DeleteObjects is the one call S3 requires a body MD5 for.
          "content-md5": createHash("md5").update(body).digest("base64"),
        },
        body,
      });
      if (!res.ok) await this.fail(res, "Deleting objects");
      const text = await res.text();
      if (/<Error>/.test(text)) {
        const detail = [tag(text, "Key"), tag(text, "Code")].filter(Boolean).join(": ");
        throw new StorageError(`Some objects could not be deleted — ${detail}`, 502);
      }
    }
  }

  async exists(key: string): Promise<boolean> {
    return (await this.getMetadata(key)) !== null;
  }

  async list(
    prefix: string, opts: { limit?: number; cursor?: string } = {},
  ): Promise<{ objects: ObjectMetadata[]; cursor: string | null }> {
    const query: Record<string, string> = {
      "list-type": "2",
      prefix,
      "max-keys": String(Math.min(1000, Math.max(1, opts.limit ?? 1000))),
    };
    if (opts.cursor) query["continuation-token"] = opts.cursor;
    const res = await this.send({ method: "GET", key: "", query });
    if (!res.ok) await this.fail(res, "Listing objects");
    const text = await res.text();
    const objects: ObjectMetadata[] = [];
    for (const item of blocks(text, "Contents")) {
      const key = tag(item, "Key");
      if (!key) continue;
      const modified = tag(item, "LastModified");
      objects.push({
        key,
        size: Number(tag(item, "Size") ?? 0) || 0,
        contentType: null,
        etag: unquote(tag(item, "ETag")),
        lastModified: modified ? new Date(modified) : null,
      });
    }
    const truncated = tag(text, "IsTruncated") === "true";
    return { objects, cursor: truncated ? tag(text, "NextContinuationToken") : null };
  }
}

/**
 * Build a provider from the environment, or say why not.
 *
 * Returns `null` rather than throwing when nothing is configured, so a
 * deployment without R2 answers 501 "media storage is not configured" on the
 * routes that need it and runs normally everywhere else — the same shape
 * `aiConfigured()` already uses for the AI provider.
 */
export function r2FromEnv(env: NodeJS.ProcessEnv = process.env): R2StorageProvider | null {
  const endpoint = env.R2_ENDPOINT
    ?? (env.R2_ACCOUNT_ID ? `https://${env.R2_ACCOUNT_ID}.r2.cloudflarestorage.com` : "");
  const bucket = env.R2_BUCKET ?? "";
  const accessKeyId = env.R2_ACCESS_KEY_ID ?? "";
  const secretAccessKey = env.R2_SECRET_ACCESS_KEY ?? "";
  if (!endpoint || !bucket || !accessKeyId || !secretAccessKey) return null;
  return new R2StorageProvider({
    endpoint, bucket, accessKeyId, secretAccessKey,
    region: env.R2_REGION || "auto",
    forcePathStyle: env.R2_FORCE_PATH_STYLE !== "0",
  });
}

/** Which setting is missing — for the 501 body, never for a log with secrets in it. */
export function r2MissingSettings(env: NodeJS.ProcessEnv = process.env): string[] {
  const missing: string[] = [];
  if (!env.R2_ENDPOINT && !env.R2_ACCOUNT_ID) missing.push("R2_ACCOUNT_ID (or R2_ENDPOINT)");
  if (!env.R2_BUCKET) missing.push("R2_BUCKET");
  if (!env.R2_ACCESS_KEY_ID) missing.push("R2_ACCESS_KEY_ID");
  if (!env.R2_SECRET_ACCESS_KEY) missing.push("R2_SECRET_ACCESS_KEY");
  return missing;
}
