/**
 * THE PUBLIC REFERENCE PAGES, GENERATED FROM THE CODE (Research Engine
 * audit, Phase 7 — public developer documentation).
 *
 * Three pages of the public docs are catalogues the code already holds:
 * the question types and their variants (the schema's registries), the
 * logic language (operators, functions, piping properties, the UX script
 * API, the punch verbs, the analysis vocabulary) and the Intelligent-mode
 * action vocabulary (the TypeScript unions in the engine). They are
 * generated here so they cannot drift from the code, and a test keeps the
 * committed files equal to what this module generates.
 *
 *   node scripts/gen-public-docs.mjs            write the pages
 *   node scripts/gen-public-docs.mjs --check    exit 1 when a page is stale
 */
import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const DOCS_DIR = join(ROOT, "apps", "studio", "content", "docs");

const esc = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
const code = (s) => `\`${String(s)}\``;
const row = (cells) => `| ${cells.map(esc).join(" | ")} |`;
const table = (head, rows) => [row(head), `|${head.map(() => "---").join("|")}|`, ...rows.map(row)].join("\n");
const STAMP = "<!-- generated by scripts/gen-public-docs.mjs — do not edit by hand -->";

/** the TypeScript text of a type or const from a source file, from its `export …` line to the first line that ends it */
function sourceBlock(file, startRe, endRe = /^;?\s*$|^\};?$|;$/) {
  const lines = readFileSync(join(ROOT, file), "utf8").split("\n");
  const start = lines.findIndex((l) => startRe.test(l));
  if (start < 0) throw new Error(`${file}: ${startRe} not found`);
  const out = [lines[start]];
  if (endRe.test(lines[start]) && !/=\s*$/.test(lines[start])) return lines[start];
  for (let i = start + 1; i < lines.length; i++) {
    out.push(lines[i]);
    if (endRe.test(lines[i])) break;
  }
  return out.join("\n");
}

export async function generate() {
  const engine = await import(join(ROOT, "packages", "engine", "dist", "index.js"));
  const schema = await import(join(ROOT, "packages", "schema", "dist", "index.js"));
  return {
    "question-types.md": questionTypes(engine, schema),
    "logic-reference.md": logicReference(engine, schema),
    "actions-reference.md": actionsReference(engine),
  };
}

/* ------------------------------------------------------------ question types */

function questionTypes(engine, schema) {
  const plugins = schema.questionTypeRegistry.all();
  const variants = schema.QUESTION_VARIANTS;
  const out = [];
  out.push(STAMP, "", "# Question types", "", "Every question in a ReScript definition has a `type` (the base type, which decides what answer is stored and how it exports) and, usually, a `variant` (`\"<family>.<key>\"`, which decides how it is presented and which capabilities the editor offers). A variant always resolves to one base type. The Intelligent-mode action `create_question` accepts either a base type, a variant id, or one of the friendly names listed in the actions reference.", "");
  out.push("## Base types", "", `${plugins.length} base types. The response model says what the stored answer is; the export columns follow from it (see *Data and exports*).`, "");
  const features = (f) => Object.entries(f ?? {}).filter(([, v]) => v).map(([k]) => k).join(", ") || "—";
  out.push(table(["type", "label", "category", "response model", "features"], plugins.map((p) => [code(p.type), p.label, p.category, code(schema.responseModelOf(p.type)), features(p.features)])));
  out.push("", "## Variants by family", "", `${variants.length} variants in ${new Set(variants.map((v) => v.family)).size} families. *retired → X* means the variant is hidden from the picker but still renders (use X for new questions); *preset of X* means it is X with defaults applied.`, "");
  const families = [...new Set(variants.map((v) => v.family))];
  for (const fam of families) {
    const vs = variants.filter((v) => v.family === fam);
    out.push(`### ${vs[0].familyLabel} (\`${fam}\`)`, "");
    out.push(table(["variant", "name", "base type", "capabilities", "validations", "notes"], vs.map((v) => [code(v.id), v.name, code(v.baseType), (v.capabilities ?? []).join(", ") || "—", (v.validations ?? []).join(", ") || "—", [v.supersededBy ? `retired → ${v.supersededBy}` : "", v.presetOf ? `preset of ${v.presetOf}` : "", v.pickerReplacedBy ? `replaced by ${v.pickerReplacedBy}` : "", v.renderer ? `renderer ${v.renderer}` : "", v.scale ? `scale ${v.scale.min}–${v.scale.max}${v.scale.fixed ? " fixed" : ""}` : "", v.status !== "stable" ? v.status : ""].filter(Boolean).join("; ") || "—"])));
    out.push("");
  }
  out.push("## Capabilities", "", "A capability names something the editor offers for the variant: " + [...new Set(variants.flatMap((v) => v.capabilities ?? []))].sort().map(code).join(", ") + ".", "");
  out.push("## Validation kinds", "", "Every question accepts the universal kinds `required`, `condition`, `custom_expression` and `custom_script`; a variant's own list adds the kinds its answer supports: " + [...new Set(variants.flatMap((v) => v.validations ?? []))].sort().map(code).join(", ") + ".", "");
  return out.join("\n");
}

/* ------------------------------------------------------------ logic reference */

function logicReference(engine, schema) {
  const out = [];
  out.push(STAMP, "", "# Logic reference", "", "The vocabulary of the logic language, as the engine reads it. The narrative — how conditions, calculations, piping and set expressions fit together, with worked examples — is in *Logic and expressions*.", "");
  out.push("## Comparison operators", "", "Each operator's spellings, canonical first (the one the Studio prints). The camelCase name is always accepted.", "");
  const words = engine.OPERATOR_WORDS;
  const kinds = { valueless: new Set(schema.VALUELESS_OPERATORS), two: new Set(schema.TWO_VALUE_OPERATORS), list: new Set(schema.LIST_VALUE_OPERATORS) };
  const operand = (op) => (kinds.valueless.has(op) ? "none" : kinds.two.has(op) ? "two (`X and Y`)" : kinds.list.has(op) ? "a list `[a, b]`" : "one");
  out.push(table(["operator", "spellings", "operand"], Object.entries(words).map(([op, ws]) => [code(op), [...new Set(ws)].map(code).join(", "), operand(op)])));
  out.push("", "Connectives: `AND` / `&&`, `OR` / `||`, `NOT` / `!`, `NOR` (= NOT (A OR B)), `BUT NOT` (= AND NOT), parentheses. `NOT` binds tighter than `AND`, `AND` tighter than `OR`; mixing `AND` and `OR` without brackets is accepted with a warning.", "");
  out.push("## Operators by answer kind", "", table(["kind", "operators"], Object.entries(schema.OPERATORS_BY_KIND).map(([k, ops]) => [code(k), ops.map(code).join(", ")])), "");
  out.push("## Calculation functions", "", `${engine.CALC_FUNCTION_NAMES.length} functions, usable in calculations, in \`{{expr: …}}\` piping and inside conditions (an expression in a condition compiles to an \`expr\` source). Names are case-insensitive.`, "");
  const groups = [
    ["Aggregates", ["sum", "avg", "mean", "average", "min", "max", "count", "countif"], "`sum(Q1, Q2)`, `avg(ALLOC_*)` (a `*` wildcard over variable names), `countif(Q5_1, Q5_2, \">\", 3)`"],
    ["Arithmetic", ["pct", "percent", "weighted", "round", "abs", "floor", "ceil", "ceiling", "sqrt", "pow"], "`pct(part, whole)`, `weighted(v1, w1, v2, w2, …)`, `round(x, 2)`, `pow(x, y)`"],
    ["Logic and conversion", ["if", "coalesce", "number", "text"], "`if(Q1 > 18, 1, 0)`, `coalesce(Q2, 0)`, `number(\"12\")`, `text(Q1)`"],
    ["Strings", ["len", "length", "concat", "contains", "upper", "lower", "trim", "substring", "substr", "replace", "startswith", "endswith", "regex", "matches"], "`concat(Q1, \" \", Q2)`, `contains(Q9, \"price\")`, `substring(Q9, 0, 10)`, `replace(Q9, \"a\", \"b\")` (every occurrence, literal), `matches(Q9, \"^[A-Z]\")`"],
    ["Dates (UTC midnight)", ["today", "date", "datediff", "age", "dateadd", "year", "month", "day"], "`age(DOB)` (calendar years), `datediff(today(), date(Q7))` (days), `dateadd(Q7, 30)`"],
    ["Geo", ["distance_km"], "`distance_km(Q12, Q13)` between two location answers"],
    ["AI (server-resolved)", ["ai_classify", "ai_sentiment"], "`ai_classify(Q9, \"Price|Service|Quality\")`, `ai_sentiment(Q9)` → positive | neutral | negative — only as the whole expression of a calculated question"],
  ];
  const listed = new Set(groups.flatMap((g) => g[1]));
  const rest = engine.CALC_FUNCTION_NAMES.filter((n) => !listed.has(n));
  out.push(table(["group", "functions", "examples"], [...groups.map(([g, fs, ex]) => [g, fs.filter((f) => engine.CALC_FUNCTION_NAMES.includes(f)).map(code).join(", "), ex]), ...(rest.length ? [["Other", rest.map(code).join(", "), ""]] : [])]));
  out.push("", "Operators in a calculation: `+ - * / %`, `== != > < >= <=`, `and` / `&&`, `or` / `||`, `not` / `!`, unary `-`. Strings in double or single quotes. `+` concatenates when either side is a string. Division by zero gives null. Limits: depth 64, 20 000 steps.", "");
  out.push("## Piping", "", "A token is `{{ … }}` in any question text, instruction, option label, HTML block, end message, redirect or media URL. A question token is `{{CODE}}`, `{{CODE.property}}`, `{{CODE[row].property}}`, with an optional `|format` suffix.", "");
  out.push("### Properties", "", table(["property", "meaning", "multi-value only"], engine.PIPE_PROPERTIES.map((p) => [code(p.value), p.label, p.multiOnly ? "yes" : ""])), "");
  out.push("### Formats", "", table(["format", "meaning", "example"], engine.PIPE_FORMATS.map((f) => [code(f.value), f.label, f.example])), "", "Also `|join:<separator>`. Namespaces: `{{calc.NAME}}`, `{{ed.NAME}}` / `{{embedded.NAME}}`, `{{loop.label}}` / `.code` / `.index` / `.count` / `.<column>`, `{{<loopVar>.<column>}}` for an outer loop, `{{CURRENT_ITEM}}`, `{{LOOP_INDEX}}`, `{{LOOP_COUNT}}`, `{{expr: Q1 + Q2}}`.", "");
  out.push("## Auto-punch verbs", "", table(["action", "words"], Object.entries(engine.PUNCH_ACTION_WORDS).map(([a, ws]) => [code(a), [].concat(ws).map(code).join(", ")])), "", "Grammar: `IF <condition> THEN <VERB> Q2.B[, Q2.C] [AND <VERB> Q3.X]`, `ELSE IF <condition> THEN …`, `ELSE <VERB> …`, `SET <Question|VARIABLE> = <code|label|number|\"text\">`, `CLEAR <Question>`.", "");
  out.push("## UX behaviour scripts", "", "A behaviour's `script` runs in a sandboxed iframe as `new Function(\"rs\", code)` with a frozen `rs`. Functions: " + engine.UX_SCRIPT_API.map(code).join(", ") + ". Events: " + engine.UX_SCRIPT_EVENTS.map(code).join(", ") + ". Aliases: " + Object.entries(engine.UX_SCRIPT_EVENT_ALIASES).map(([a, b]) => `${code(a)} → ${code(b)}`).join(", ") + ". Loops, `eval`, `fetch`, `document`, `window` and any attempt to set an answer are rejected before the script is saved; commands are rate-limited to 200 per second.", "");
  out.push("## Analysis vocabulary", "", `Roles: ${schema.ANALYSIS_ROLES.map(code).join(", ")}.`, "", `Measurement levels: ${schema.MEASUREMENT_LEVELS.map(code).join(", ")}.`, "", `Methods: ${schema.ANALYSIS_METHODS.map(code).join(", ")}.`, "");
  out.push("## Flow node types", "", table(["type", "label"], Object.entries(engine.FLOW_TYPE_LABELS).map(([t, l]) => [code(t), l])), "");
  return out.join("\n");
}

/* ------------------------------------------------------------ actions reference */

function actionsReference(engine) {
  const out = [];
  out.push(STAMP, "", "# Actions reference", "", "Intelligent mode changes a survey only through ACTIONS: a closed vocabulary of operations the engine validates and applies to a copy of the definition before anything is shown for approval. A sentence the engine reads becomes actions; a language model's answer is actions too, in the same vocabulary, through the same gate. Every action names its objects by question code (`Q7`), variable name (`AGE`), option code or label, block title or batch ref (`ref` on a `create_*` action, usable by later actions in the same batch). Conditions (`CondInput`) are the text logic language or a JSON `Condition`.", "");
  const ops = (name, list) => `**${name}** (${list.length}): ${list.map(code).join(", ")}`;
  out.push("## The operations", "", ops("Survey", engine.SURVEY_ACTION_OPS.filter((o) => !engine.UX_ACTION_OPS.includes(o) && !engine.ANALYSIS_ACTION_OPS.includes(o) && !engine.LOCALIZATION_ACTION_OPS.includes(o) && !engine.QUOTA_ACTION_OPS.includes(o) && !engine.OPTION_ACTION_OPS.includes(o))), "", ops("Options and design", engine.OPTION_ACTION_OPS), "", ops("Look and behaviour (UX)", engine.UX_ACTION_OPS), "", ops("Analysis", engine.ANALYSIS_ACTION_OPS), "", ops("Localization", engine.LOCALIZATION_ACTION_OPS), "", ops("Quotas", engine.QUOTA_ACTION_OPS), "");
  const block = (title, file, re, end) => { out.push(`## ${title}`, "", `From \`${file}\`:`, "", "```ts", sourceBlock(file, re, end), "```", ""); };
  block("Survey actions", "packages/engine/src/surveyActions.ts", /^export type SurveyAction =/, /^\s*\| OptionAction;?\s*$/);
  out.push("Supporting types:", "", "```ts", sourceBlock("packages/engine/src/surveyActions.ts", /^export type OptionSpec =/, /;\s*$/), sourceBlock("packages/engine/src/surveyActions.ts", /^export interface ScaleSpec/, /\}\s*$/), sourceBlock("packages/engine/src/surveyActions.ts", /^export interface ValidationSpec/, /\}\s*$/), "```", "");
  block("Option and design actions", "packages/engine/src/optionActions.ts", /^export type OptionAction =/, /;\s*$/);
  block("UX actions", "packages/engine/src/uxActions.ts", /^export type UxAction =/, /;\s*$/);
  block("Analysis actions", "packages/engine/src/analysisActions.ts", /^export type AnalysisAction =/, /;\s*$/);
  block("Localization actions", "packages/engine/src/localizationActions.ts", /^export type LocalizationAction =/, /;\s*$/);
  block("Quota actions", "packages/engine/src/quotaActions.ts", /^export type QuotaAction =/, /;\s*$/);
  out.push("## Friendly type names", "", "`create_question.type` and `update_question.type` accept a base type, a variant id, or one of these names:", "", "```ts", sourceBlock("packages/engine/src/surveyActions.ts", /^(export )?const ACTION_TYPES/, /^\};?\s*$/), "```", "");
  return out.join("\n");
}
