import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { renderMarkdown, type RenderedDoc } from "./markdown.ts";

/**
 * THE PUBLIC DOCUMENTATION PAGES (Phase 7). Markdown files in
 * `apps/studio/content/docs`, one page per file, `index.md` the front page.
 * Read from disk on each request (they are small and the route is dynamic),
 * so a deploy that changes a page needs no code change. The order and the
 * one-line descriptions here are the site's navigation and `llms.txt`.
 */
export interface DocPage { slug: string; title: string; description: string; generated: boolean }

export const DOC_ORDER: { slug: string; description: string }[] = [
  { slug: "index", description: "What ReScript Studio is and how these pages are organised" },
  { slug: "getting-started", description: "The three ways to program a survey, a complete minimal definition, test and live" },
  { slug: "survey-definition", description: "The JSON model: meta, questions, options, flow, calculations, embedded data, and where everything else lives" },
  { slug: "question-types", description: "All base types and variants with their response models, capabilities and validations (generated from the code)" },
  { slug: "logic", description: "Conditions in text and JSON, display and skip logic, validation, calculations, named and set expressions, masks, auto-punch" },
  { slug: "logic-reference", description: "Every operator, calculation function, piping property and format, the UX script API, the analysis vocabulary (generated)" },
  { slug: "piping-and-lists", description: "Piping tokens, carry-forward, option logic and list operations, randomization, List Fill, loops" },
  { slug: "custom-code", description: "HTML blocks, per-question HTML/CSS/JS, survey scripts and their API, the UX layer and its sandboxed rs API, branding code" },
  { slug: "intelligent-mode", description: "Programming in sentences: the engine's reading, the model's turn, actions, approval and history, the workflow, execution modes, tiers and cost" },
  { slug: "actions-reference", description: "The closed vocabulary of operations every change goes through, with their fields (generated)" },
  { slug: "research-engine", description: "The research design, the analysis plan, coverage and enforcement, runs and findings, the proposal, report and deck, the workflow" },
  { slug: "data-and-exports", description: "What each type stores, export columns, datasets, CSV/Excel/SPSS/SAS/Stata/JSON, the variable dictionary, quality" },
  { slug: "localization-and-quotas", description: "Languages, translation keys, routing, the glossary; quotas, cells, quota checks; embedded data" },
  { slug: "api", description: "Authentication, the Studio routes by area with the capability each needs, the respondent runtime endpoints" },
];

/** where the pages are: beside the app (the deploy includes them), or the repo checkout when run from elsewhere */
export function docsDir(): string {
  const candidates = [join(process.cwd(), "content", "docs"), join(process.cwd(), "apps", "studio", "content", "docs")];
  return candidates.find((d) => existsSync(d)) ?? candidates[0];
}

export function readDoc(slug: string): string | null {
  if (!/^[a-z0-9-]+$/.test(slug)) return null;
  const path = join(docsDir(), `${slug}.md`);
  return existsSync(path) ? readFileSync(path, "utf8") : null;
}

export function listDocs(): DocPage[] {
  const dir = docsDir();
  const present = new Set(existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".md")).map((f) => f.slice(0, -3)) : []);
  return DOC_ORDER.filter((d) => present.has(d.slug)).map((d) => {
    const md = readDoc(d.slug) ?? "";
    const title = /^#\s+(.+)$/m.exec(md)?.[1]?.replace(/`/g, "") ?? d.slug;
    return { slug: d.slug, title, description: d.description, generated: md.includes("generated by scripts/gen-public-docs.mjs") };
  });
}

export function renderDoc(slug: string): (RenderedDoc & { slug: string }) | null {
  const md = readDoc(slug);
  if (md === null) return null;
  return { slug, ...renderMarkdown(md) };
}

/** llms.txt: the index AI tools read first — the site, one line per page, the full text's address */
export function llmsIndex(base: string): string {
  const pages = listDocs();
  return [
    "# ReScript Studio",
    "",
    "> ReScript Studio is a survey programming platform: a visual editor, a JSON survey definition, a text logic language, a scripting surface and an Intelligent mode in which a researcher programs the survey in plain language and approves every change. These pages document how to program it; three reference pages are generated from the platform's code.",
    "",
    "## Docs",
    "",
    ...pages.map((p) => `- [${p.title}](${base}/docs/${p.slug}.md): ${p.description}`),
    "",
    "## Optional",
    "",
    `- [Everything in one file](${base}/llms-full.txt): all pages concatenated, for a tool that reads once`,
    "",
  ].join("\n");
}

/** llms-full.txt: every page, in order, as markdown */
export function llmsFull(): string {
  return listDocs().map((p) => `<!-- page: ${p.slug} -->\n${readDoc(p.slug) ?? ""}`).join("\n\n---\n\n");
}
