import { z } from "zod";
import { money6 } from "./money.js";

/**
 * THE COST & PRICING REGISTRY and THE BILLABLE EVENT REGISTRY.
 *
 * Two tables, both editable by an administrator, both extensible without
 * touching the metering code:
 *
 *   billable events — WHAT can be charged for (AI_REQUEST, TRANSLATION_CHARACTER,
 *     SURVEY_RESPONSE, STORAGE_GB, …): its category on the dashboard, the unit
 *     it is counted in, and whether it is billable at all. A feature that
 *     wants to be metered registers an event type; nothing else changes.
 *
 *   rates — WHAT IT COSTS: per provider / service / model, the provider's
 *     price per unit-size (Google: $20 per 1,000,000 characters), an optional
 *     markup, an optional fixed customer rate, effective dates, active flag.
 *     The metering engine looks the rate up at the time of the event and
 *     prices from it; nothing in a route or a component knows a price.
 */

export const USAGE_CATEGORIES = ["ai", "translation", "responses", "storage", "bandwidth", "infrastructure", "voice", "export", "processing", "other"] as const;
export type UsageCategory = (typeof USAGE_CATEGORIES)[number];
export const CATEGORY_LABEL: Record<UsageCategory, string> = {
  ai: "AI", translation: "Translation", responses: "Responses", storage: "Storage", bandwidth: "Bandwidth",
  infrastructure: "Infrastructure", voice: "Voice", export: "Exports & reports", processing: "Data processing", other: "Other",
};

export const USAGE_UNITS = ["request", "token", "character", "word", "response", "session", "page", "question", "MB", "GB", "GB-month", "minute", "second", "file", "message", "item", "unit"] as const;
export type UsageUnit = (typeof USAGE_UNITS)[number];

export const BillableEventDef = z.object({
  type: z.string().min(1).max(64).regex(/^[A-Z][A-Z0-9_]*$/, "UPPER_SNAKE_CASE"),
  label: z.string().min(1),
  category: z.enum(USAGE_CATEGORIES),
  unit: z.enum(USAGE_UNITS),
  billable: z.boolean().default(true),
  /** the registry entry that prices it, unless the event carries its own provider/service/model */
  rate: z.object({ provider: z.string(), service: z.string(), model: z.string().nullable().optional() }).nullable().optional(),
  description: z.string().default(""),
  active: z.boolean().default(true),
});
export type BillableEventDef = z.infer<typeof BillableEventDef>;

/** The events the platform ships with. An administrator can add, disable or re-unit any of them. */
export const DEFAULT_BILLABLE_EVENTS: BillableEventDef[] = [
  { type: "AI_REQUEST", label: "AI request", category: "ai", unit: "request", billable: true, rate: null, description: "One call to the AI model — priced from its input and output tokens (AI_INPUT_TOKEN / AI_OUTPUT_TOKEN rates).", active: true },
  { type: "AI_INPUT_TOKEN", label: "AI input tokens", category: "ai", unit: "token", billable: true, rate: null, description: "Tokens sent to the model.", active: true },
  { type: "AI_OUTPUT_TOKEN", label: "AI output tokens", category: "ai", unit: "token", billable: true, rate: null, description: "Tokens generated by the model.", active: true },
  { type: "TRANSLATION_CHARACTER", label: "Translation characters", category: "translation", unit: "character", billable: true, rate: null, description: "Characters sent to the translation provider (cached results are free).", active: true },
  { type: "TRANSLATION_REQUEST", label: "Translation request", category: "translation", unit: "request", billable: false, rate: null, description: "One batch request to the provider; non-billable by default (characters are what cost).", active: true },
  { type: "SURVEY_RESPONSE", label: "Survey response", category: "responses", unit: "response", billable: true, rate: { provider: "rescript", service: "runtime", model: "response" }, description: "One completed interview.", active: true },
  { type: "SURVEY_RESPONSE_STARTED", label: "Response started", category: "responses", unit: "response", billable: false, rate: { provider: "rescript", service: "runtime", model: "response_started" }, description: "One started interview; non-billable by default.", active: true },
  { type: "SURVEY_SESSION", label: "Survey session", category: "responses", unit: "session", billable: false, rate: null, description: "A runtime session; non-billable by default.", active: true },
  { type: "SURVEY_RENDER", label: "Page rendered", category: "infrastructure", unit: "page", billable: false, rate: null, description: "A survey page served; non-billable by default.", active: true },
  { type: "API_REQUEST", label: "API request", category: "infrastructure", unit: "request", billable: false, rate: null, description: "A runtime API call; non-billable by default.", active: true },
  { type: "STORAGE_GB", label: "File storage", category: "storage", unit: "GB-month", billable: true, rate: { provider: "supabase", service: "storage", model: "gb_month" }, description: "Stored files, per GB per month.", active: true },
  { type: "FILE_UPLOAD", label: "File upload", category: "storage", unit: "MB", billable: true, rate: { provider: "supabase", service: "storage", model: "upload_mb" }, description: "Respondent or studio file uploaded, per MB.", active: true },
  { type: "BANDWIDTH_GB", label: "Bandwidth", category: "bandwidth", unit: "GB", billable: true, rate: { provider: "supabase", service: "bandwidth", model: "egress_gb" }, description: "Data transferred, per GB.", active: true },
  { type: "DATABASE_STORAGE_GB", label: "Database storage", category: "infrastructure", unit: "GB-month", billable: false, rate: { provider: "supabase", service: "database", model: "gb_month" }, description: "Database size, per GB per month — reported when metered.", active: true },
  { type: "VOICE_MINUTE", label: "Voice minutes", category: "voice", unit: "minute", billable: true, rate: null, description: "Voice interview audio, per minute.", active: true },
  { type: "TEXT_TO_SPEECH_CHARACTER", label: "Text-to-speech characters", category: "voice", unit: "character", billable: true, rate: null, description: "Characters synthesised into speech.", active: true },
  { type: "SPEECH_TO_TEXT_MINUTE", label: "Speech-to-text minutes", category: "voice", unit: "minute", billable: true, rate: null, description: "Audio transcribed, per minute.", active: true },
  { type: "AUDIO_PROCESSING_MINUTE", label: "Audio processing", category: "voice", unit: "minute", billable: true, rate: null, description: "Audio processed, per minute.", active: true },
  { type: "VIDEO_PROCESSING_MINUTE", label: "Video processing", category: "processing", unit: "minute", billable: true, rate: null, description: "Video processed, per minute.", active: true },
  { type: "GEOCODE_REQUEST", label: "Geocoding request", category: "other", unit: "request", billable: true, rate: { provider: "geocode", service: "lookup", model: null }, description: "One address lookup.", active: true },
  { type: "EMAIL_MESSAGE", label: "Email invitation", category: "other", unit: "message", billable: true, rate: { provider: "resend", service: "email", model: null }, description: "One invitation or reminder email.", active: true },
  { type: "REPORT_GENERATION", label: "Report generated", category: "export", unit: "file", billable: false, rate: { provider: "rescript", service: "analytics", model: "report" }, description: "A PowerPoint / Excel report built; non-billable by default.", active: true },
  { type: "EXPORT_GENERATION", label: "Data export", category: "export", unit: "file", billable: false, rate: { provider: "rescript", service: "export", model: "dataset" }, description: "A dataset download; non-billable by default.", active: true },
  { type: "DATA_PROCESSING", label: "Data processing", category: "processing", unit: "unit", billable: false, rate: null, description: "Quality scoring, recounts and other batch processing; non-billable by default.", active: true },
  { type: "CUSTOM_EVENT", label: "Custom event", category: "other", unit: "unit", billable: true, rate: null, description: "A feature-defined event priced by its own provider/service/model.", active: true },
];

export const Rate = z.object({
  id: z.string().min(1),
  provider: z.string().min(1),          // google | openai-compatible | anthropic | supabase | rescript | resend | geocode | …
  service: z.string().min(1),           // translate | chat | tts | storage | runtime | …
  model: z.string().nullable().default(null),   // claude-sonnet-4-6 | gpt-4o-mini | v2 | gb_month | …
  /** which side of a two-sided price this row is: input / output tokens; null for single-sided */
  side: z.enum(["input", "output"]).nullable().default(null),
  unit: z.enum(USAGE_UNITS),
  /** the provider's price for `unitSize` units, in `currency` */
  providerCost: z.number().min(0),
  unitSize: z.number().positive().default(1),   // 1_000_000 for per-million pricing
  /** an extra markup on this rate alone, on top of the global third-party markup */
  markupPct: z.number().min(0).max(1000).default(0),
  /** a fixed customer price per `unitSize` units — bypasses the pricing model when set */
  customerRate: z.number().min(0).nullable().default(null),
  currency: z.string().default("USD"),
  effectiveFrom: z.string().nullable().default(null),   // ISO date
  effectiveUntil: z.string().nullable().default(null),
  active: z.boolean().default(true),
  /** infrastructure estimate rather than a vendor invoice line */
  estimated: z.boolean().default(false),
  note: z.string().default(""),
});
export type Rate = z.infer<typeof Rate>;

const M = 1_000_000;
/**
 * Starting rates — list prices as published in 2026, to be maintained from
 * the administration screen. Every AI model is a row; an unknown model falls
 * back to the provider's `*` row so a new model is metered from day one at a
 * conservative price rather than for free.
 */
export const DEFAULT_RATES: Rate[] = [
  // Google Cloud Translation v2 — $20 per million characters
  { id: "google.translate.v2", provider: "google", service: "translate", model: "v2", side: null, unit: "character", providerCost: 20, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "Cloud Translation Basic list price" },
  { id: "google.translate.*", provider: "google", service: "translate", model: "*", side: null, unit: "character", providerCost: 20, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "fallback for any Google translation model" },
  { id: "deepl.translate.*", provider: "deepl", service: "translate", model: "*", side: null, unit: "character", providerCost: 25, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: false, estimated: false, note: "enable when a DeepL adapter is configured" },
  { id: "microsoft.translate.*", provider: "microsoft", service: "translate", model: "*", side: null, unit: "character", providerCost: 10, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: false, estimated: false, note: "enable when an Azure Translator adapter is configured" },
  // AI chat models (OpenAI-compatible endpoint; provider id is the endpoint kind, model is the model string)
  { id: "ai.chat.claude-sonnet-4-6.in", provider: "openai-compatible", service: "chat", model: "claude-sonnet-4-6", side: "input", unit: "token", providerCost: 3, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "" },
  { id: "ai.chat.claude-sonnet-4-6.out", provider: "openai-compatible", service: "chat", model: "claude-sonnet-4-6", side: "output", unit: "token", providerCost: 15, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "" },
  { id: "ai.chat.claude-haiku-4-5.in", provider: "openai-compatible", service: "chat", model: "claude-haiku-4-5", side: "input", unit: "token", providerCost: 1, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "" },
  { id: "ai.chat.claude-haiku-4-5.out", provider: "openai-compatible", service: "chat", model: "claude-haiku-4-5", side: "output", unit: "token", providerCost: 5, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "" },
  { id: "ai.chat.gpt-4o-mini.in", provider: "openai-compatible", service: "chat", model: "gpt-4o-mini", side: "input", unit: "token", providerCost: 0.15, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "" },
  { id: "ai.chat.gpt-4o-mini.out", provider: "openai-compatible", service: "chat", model: "gpt-4o-mini", side: "output", unit: "token", providerCost: 0.6, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "" },
  { id: "ai.chat.*.in", provider: "openai-compatible", service: "chat", model: "*", side: "input", unit: "token", providerCost: 3, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "fallback for a model with no row of its own" },
  { id: "ai.chat.*.out", provider: "openai-compatible", service: "chat", model: "*", side: "output", unit: "token", providerCost: 15, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "fallback for a model with no row of its own" },
  // speech
  { id: "ai.tts.*", provider: "openai-compatible", service: "tts", model: "*", side: null, unit: "character", providerCost: 15, unitSize: M, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "text-to-speech per character" },
  { id: "ai.stt.*", provider: "openai-compatible", service: "stt", model: "*", side: null, unit: "minute", providerCost: 0.006, unitSize: 1, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "speech-to-text per audio minute" },
  { id: "browser.speech", provider: "browser", service: "speech", model: "*", side: null, unit: "minute", providerCost: 0, unitSize: 1, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "Web Speech API in the respondent's browser — free" },
  // platform / infrastructure estimates
  { id: "rescript.runtime.response", provider: "rescript", service: "runtime", model: "response", side: null, unit: "response", providerCost: 0, unitSize: 1, markupPct: 0, customerRate: 0.02, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: true, note: "customer price per completed interview; infrastructure share comes from the config estimate" },
  { id: "rescript.runtime.response_started", provider: "rescript", service: "runtime", model: "response_started", side: null, unit: "response", providerCost: 0, unitSize: 1, markupPct: 0, customerRate: 0, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: true, note: "" },
  { id: "supabase.storage.gb_month", provider: "supabase", service: "storage", model: "gb_month", side: null, unit: "GB-month", providerCost: 0.021, unitSize: 1, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: true, note: "" },
  { id: "supabase.storage.upload_mb", provider: "supabase", service: "storage", model: "upload_mb", side: null, unit: "MB", providerCost: 0.00005, unitSize: 1, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: true, note: "write + first month of storage per MB" },
  { id: "supabase.bandwidth.egress_gb", provider: "supabase", service: "bandwidth", model: "egress_gb", side: null, unit: "GB", providerCost: 0.09, unitSize: 1, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: true, note: "" },
  { id: "supabase.database.gb_month", provider: "supabase", service: "database", model: "gb_month", side: null, unit: "GB-month", providerCost: 0.125, unitSize: 1, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: true, note: "" },
  { id: "geocode.lookup", provider: "geocode", service: "lookup", model: "*", side: null, unit: "request", providerCost: 0.005, unitSize: 1, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "" },
  { id: "resend.email", provider: "resend", service: "email", model: "*", side: null, unit: "message", providerCost: 0.0004, unitSize: 1, markupPct: 0, customerRate: null, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: false, note: "" },
  { id: "rescript.analytics.report", provider: "rescript", service: "analytics", model: "report", side: null, unit: "file", providerCost: 0, unitSize: 1, markupPct: 0, customerRate: 0, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: true, note: "" },
  { id: "rescript.export.dataset", provider: "rescript", service: "export", model: "dataset", side: null, unit: "file", providerCost: 0, unitSize: 1, markupPct: 0, customerRate: 0, currency: "USD", effectiveFrom: null, effectiveUntil: null, active: true, estimated: true, note: "" },
];

export interface RateQuery { provider: string; service: string; model?: string | null; side?: "input" | "output" | null; at?: Date | string }

function inEffect(r: Rate, at: number): boolean {
  if (!r.active) return false;
  if (r.effectiveFrom && Date.parse(r.effectiveFrom) > at) return false;
  if (r.effectiveUntil && Date.parse(r.effectiveUntil) <= at) return false;
  return true;
}

/**
 * The rate for a provider/service/model at a moment: an exact model row
 * first, then the provider's `*` row. Two rows for the same key → the one
 * whose `effectiveFrom` is latest.
 */
export function findRate(rates: Rate[], q: RateQuery): Rate | null {
  const at = q.at ? (typeof q.at === "string" ? Date.parse(q.at) : q.at.getTime()) : Date.now();
  const side = q.side ?? null;
  const pick = (model: string | null) => rates
    .filter((r) => r.provider === q.provider && r.service === q.service && (r.model ?? null) === model && (r.side ?? null) === side && inEffect(r, at))
    .sort((a, b) => Date.parse(b.effectiveFrom ?? "1970-01-01") - Date.parse(a.effectiveFrom ?? "1970-01-01"))[0] ?? null;
  return pick(q.model ?? null) ?? (q.model != null ? pick("*") : null) ?? pick(null) ?? null;
}

/** Provider cost of `quantity` units under a rate (with the rate's own markup applied). */
export function providerCostFor(rate: Rate | null, quantity: number): number {
  if (!rate || !Number.isFinite(quantity) || quantity <= 0) return 0;
  return money6((quantity / rate.unitSize) * rate.providerCost * (1 + rate.markupPct / 100));
}

/** Fixed customer price of `quantity` units, when the rate carries one. */
export function fixedChargeFor(rate: Rate | null, quantity: number): number | null {
  if (!rate || rate.customerRate == null || quantity <= 0) return null;
  return money6((quantity / rate.unitSize) * rate.customerRate);
}

export function eventDef(events: BillableEventDef[], type: string): BillableEventDef | null {
  return events.find((e) => e.type === type) ?? null;
}

/** Register a new billable event at runtime (a feature module can call this at import time). */
export function registerBillableEvent(events: BillableEventDef[], def: BillableEventDef): BillableEventDef[] {
  const parsed = BillableEventDef.parse(def);
  const i = events.findIndex((e) => e.type === parsed.type);
  if (i < 0) return [...events, parsed];
  const next = events.slice(); next[i] = parsed; return next;
}
